apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: fargate-node
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
