apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-aws-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dlopezb93/sample-argocd-nginx-deployment.git
    targetRevision: main
    path: charts/nginx
    helm:
      valueFiles:
        - values.yaml # the main values file
        - values-{{var.STAGE}}.yaml # this is your extra values file
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
